### Install Visual Studio Code extension: REST Client  humao.rest-client

### user
POST http://localhost:8089/node/register HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "account": {
    "userid": "user",
    "password": "user",
    "roles": ["Public", "User", "Notify", "Editor"]
  }
}

### guest - created by admin with Public role only
POST http://localhost:8089/node/register HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "account": {
    "userid": "guest",
    "password": "guest",
    "roles": ["Public"]
  }
}

### admin - should be created with source schema
POST http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "account": {
    "userid": "admin",
    "password": "admin",
    "roles": ["Public","User","Admin"]
  }
}
