### doc one
PUT http://localhost:8089/my-api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "doc": {
    "docid": "doc one",
    "compilation": ["storage-node", "Storage API"],
    "title": "Document One",
    "context": ["keyword1", "key phrase two", "heart"],
    "author": "DL",
    "dateline": "Mon Apr 1, 2019 1:30PM",
    "format": "md",
    "article": "Some markup for the document.",
    "created": null,
    "updated": null
  }
}

### doc two
PUT http://localhost:8089/my-api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "doc": {
    "docid": "doc two",
    "compilation": ["storage-node", "Accounts API"],
    "title": "Document Two",
    "context": "keyword1, key phrase two ,heart",
    "author": "DL",
    "format": "md",
    "article": "Some markup for the document."
  }
}

### doc three
PUT http://localhost:8089/my-api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "doc": {
    "docid": "doc three",
    "compilation": ["storage-junctions", "Engram"],
    "title": "Engram",
    "context": "keyword1, key phrase two ,engram",
    "author": "DL",
    "format": "md",
    "article": "Some markup for the Engram class.",
    "byline": "by Drew Letcher for the Evening Post"
  }
}

