### user User
PUT http://localhost:8089/my-api/settings/myfavs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "settings": {
    "category": "music",
    "genre": "rock-n-roll",
    "favorites": ["The Beatles", "The Rolling Stones", "The Hollies"]
  }
}

### user User
GET http://localhost:8089/my-api/settings/myfavs HTTP/1.1
Authorization: Basic user user

### guest Public
PUT http://localhost:8089/my-api/settings/myfavs HTTP/1.1
Authorization: Basic guest guest

{
  "settings": {
    "category": "music",
    "genre": "rock-n-roll",
    "favorites": ["The Beatles", "The Rolling Stones"]
  }
}

