
### user - update with Notify role
PUT http://localhost:8089/node/account HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
  "account": {
    "userid": "user",
    "password": "user",
    "roles": ["Public","User","ETL","Editor","Notify"],
    "settings": {
      "homepage": "/home",
      "theme": "dark"
    }
  }
}

