### doc one
PUT http://localhost:8089/api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "doc": {
    "docid": "doc one",
    "title": "Document One",
    "context": ["keyword1", "key phrase two", "heart"],
    "format": "md",
    "author": "DL",
    "timestamp": null,
    "content": "Some markup for the document."
  }
}

### doc two
PUT http://localhost:8089/api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "doc": {
    "docid": "doc two",
    "title": "Document Two",
    "context": "keyword1, key phrase two ,heart",
    "format": "md",
    "author": "DL",
    "timestamp": null,
    "content": "Some markup for the document."
  }
}


### user
GET http://localhost:8089/api/docs/doc%20one HTTP/1.1
Authorization: Basic user user

### user
GET http://localhost:8089/api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "match": {
    "key": "doc two"
  }
}

### user
POST http://localhost:8089/api/docs HTTP/1.1
Authorization: Basic user user
Content-Type: application/json

{
  "pattern": {
    "match": {
      "keyword": "keyword1"
    },
    "cues": {
      "fields": ["docid", "title"]
    }
  }
}
